### ISSUE TITLE
View tracking issue with ad blockers

### ISSUE THREAD

**Issue by jegra** [doublesecretagency/craft-adwizard#1]
When users have ad blockers installed, ads will be prevented from being displayed, but they still register as having been viewed in the admin dashboard.  Please note this refers to the version for Craft 2.

**Comment by lindseydiloreto** [comment]
Thanks for filing this. I don't have an ETA, but I'll look into it when I get a chance.

**Comment by bencroker** [comment]
Ad images are likely not appearing if the asset folder name has "ad" or "ads" or similar references to "advertisement" in it.

I notice that AdBlocker is blocking the `adwizard.js` file too. A simple workaround @lindseydiloreto would be to simply rename the file to something more generic like `tracker.js` or `wizard.js`. I've done this in my setup and it is working great.

**Comment by lindseydiloreto** [comment]
That's a great idea @bencroker! I'll try to work that into an upcoming version.

**Comment by lindseydiloreto** [comment]
I've renamed the file to `aw.js`, and will be pushing a new release out within the next few days. Once you're able to test it, please let me know if this fix does the trick for you!

Thanks for the tip @bencroker! 🍺

**Comment by bencroker** [comment]
Hoping for the next release soon!!! As noted above, this does solve the issue.

**Comment by lindseydiloreto** [comment]
Good news, **Ad Wizard 3.1.0** went out last week!

... or at least I thought it did. Looks like the branches got merged, but not properly deployed. Should be all fixed now!

Just FYI, it requires Craft 3.5, so you'll need to either update Craft first or simultaneously.

**Comment by bencroker** [comment]
Ok, so I didn't see the update as the site is still running on Craft 3.4. I'm unlikely to update this for at least a few more weeks so will continue using my fix. I would still recommend releasing this fix in AdWizard 3.0.x, for all of those sites that are not yet ready to upgrade.

**Comment by lindseydiloreto** [comment]
I probably won't be backporting it since demand was relatively low in the first place. But let me know how it works once you've updated! 👍
