### ISSUE TITLE
Allow middle mouse button click

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-adwizard#13]
Even if ads are not links, they are supposed to emulate their behaviour using Javascript.

That's why I propose adding `auxclick` event handler to ads HTML elements that would allow opening them with middle mouse button.

**Comment by lindseydiloreto** [comment]
Good news! This is already possible using the `js` and/or `attr` parts of the options parameter. 🙂

https://www.doublesecretagency.com/plugins/ad-wizard/docs/the-options-parameter
