### ISSUE TITLE
Change adwizard.js  javascript lib file name

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-adwizard#16]
The file is called `adwizard.js:`. This causes it to be blocked by scripts like ublock - `ad` part is probably making it discovered for what it really is :) Why not set file name as something like `svsgsjkfnshbkub.js`? Or allow changing filename using plugin config file.

**Comment by lindseydiloreto** [comment]
Good catch, this is indeed a known issue. @bencroker recently identified it as the root of the problem in issue #1.

I have some thoughts about making the filename more dynamic. I believe part of it would be easy, but part may be slightly trickier. If you want to help me brainstorm it, feel free to hit me up via DM! 🙂

**Comment by lindseydiloreto** [comment]
After a bit of tinkering, I decided not to make the filename dynamic. It started to seem like we'd be adding a lot of needless overhead, when simply renaming the file will (probably) work.

I've renamed the file to `aw.js`, and will be pushing a new release out within the next few days. Once you're able to test it, please let me know if this fix does the trick for you!
