### ISSUE TITLE
Ad still can be saved without URL

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-adwizard#17]
URL field has red `*` next to URL field that symbolizes that it is required. But we still can save it with this field empty. Ad just wont be displayed in such case.

Maybe make it so that in such case ad would still appear but it would do nothing when clicked?

**Comment by lindseydiloreto** [comment]
Hmm, this looks like a bug. According to the [code](https://github.com/doublesecretagency/craft-adwizard/blob/244824303033c2bda3116247a4045e032a1fd995/src/templates/ads/_main.twig#L22), past-me _intended_ for the field to be required normally... it just doesn't seem to be going through a validation process.

As a solution, I am going to simply ensure that there is something validating the URL value. Perhaps I thought Craft itself was handling that part, but it looks like I may need to write it myself.

Thanks for reporting it! 👍

**Comment by lindseydiloreto** [comment]
Alright, this is fixed for the next release. Thanks again for reporting! 🍺
