### ISSUE TITLE
project-config/apply throws error on CLI on initial install

### ISSUE THREAD

**Issue by jsmrtn** [doublesecretagency/craft-adwizard#19]
Running `project-config/apply` to install AdWizard throws an error because it attempts to redirect after install, which isn't available via CLI

```
./craft project-config/apply
Installing plugin "ad-wizard" ... error: Calling unknown method: yii\console\Response::redirect()
Aborting config apply process
```

Thanks!

**Comment by lindseydiloreto** [comment]
Good catch, thanks!

**Comment by juban** [comment]
Hi @lindseydiloreto ,

We would love to use the plugin for one of our current project but this issue is a blocker for us.
I've pushed a small pull request in order to fix the issue.
Do you have any idea when a new release that will include that will be released?

Thank you for your help.

**Comment by lindseydiloreto** [comment]
Hey @juban, sorry about that! I didn't realize this was a showstopper for you.

I've just accepted your PR, and made a "happy path" adjustment (which I should've done anyway).

Thanks for submitting that! Feel free to grab **v3.1.1** which contains those changes. 👍
