### ISSUE TITLE
FR: Make it possible to send out emails when an Ad is about to expire

### ISSUE THREAD

**Issue by michtio** [doublesecretagency/craft-adwizard#3]
A useful function for the Ad Wizard plugin would be to send out an email whenever an Ad is about to expire.

Rules should be able to configured to say "Send reminder 1 week before, Send reminder 2 weeks before, ..." or custom, to notify the user that the running ad is about to expire.

Ideally this could have more functionality to make it even more useable:

- [ ] Add email field to the ads for the user who created the ad, make this editable, whenever the site owner sells ads on their platform, the actual advertiser receives information about their ads.
- [ ] Link ad creation to users/authors just like entries

**Comment by lindseydiloreto** [comment]
I think we talked about this on Slack back in the day... If I remember correctly, the gist of it is this: Probably close to 100% of that logic belongs in a custom [business logic module](https://doublesecretagency.github.io/craft-businesslogic/).

There's nothing in Ad Wizard that tracks when something is _about_ to expire, but you could easily tap into that data via custom logic. You would also need to set a cron job to ensure that the necessary controller action gets triggered on a regular schedule.

Sending an email is outside of the scope of Ad Wizard. But again, it's easy to do this from within a custom module.

The upcoming **v2.1** will allow you to add custom fields to your ads as well. That may let you get even more creative from within your module.
