### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by bengreenbank** [doublesecretagency/craft-adwizard#30]
In the CMS, the Stats, Groups & Field Layouts sections all have a bug where the blue bottom border for the CMS panel overlaps the final list element. See screenshot:

![Screenshot 2021-07-23 at 14 12 57](https://user-images.githubusercontent.com/61185468/126786957-2cea865a-7569-4c55-8cd1-71c96f1c0d03.png)

**Comment by bengreenbank** [comment]
I am running version 3.1.2 on CraftCMS 3.6.10

**Comment by lindseydiloreto** [comment]
Try updating to 3.1.3, let me know if that fixes it...

<img width="517" alt="3 1 3@2x" src="https://user-images.githubusercontent.com/5309692/126843877-08355150-3056-4c23-be7f-a4c4f48d1aef.png">

**Comment by bengreenbank** [comment]
Hi, thanks for responding so quickly. Yes this worked. Thanks very much

**Comment by lindseydiloreto** [comment]
Ok great, glad that did the trick. 🙂
