### ISSUE TITLE
Not registering clicks

### ISSUE THREAD

**Issue by hafizovic** [doublesecretagency/craft-adwizard#42]
Hello everybody... 
Im usign Blitz caching and because of that i had an issue with 'adWizard is not defined'

After exploring, i copied superagent and aw js in suitable folder location, now i dont have that problem, but when I click on ad, click is not registered, and this is the issue that ive got
![image](https://user-images.githubusercontent.com/6839501/219910005-6748fbeb-0360-4b7c-b7c0-7065aecf047c.png)

**Comment by hafizovic** [comment]
P.S. Im using Sprig to inject ad

**Comment by hafizovic** [comment]
For everybody who have the same issue, this is my current solution

Its pretty much based on this comment [https://github.com/doublesecretagency/craft-adwizard/issues/9#issuecomment-833375065](url)

only difference is to change this
`data[window.csrfTokenName] = result; `

with 
`data['CRAFT_CSRF_TOKEN'] = result;`

**Comment by diegocosta-dev** [comment]
I have the same problem. can anyone help me?

Sprig Componente:

```
{# prettier-ignore-start #}
{% if sprig.isRequest %}
  {% set leaderboard = craft.adWizard.ads.group('leaderboard').orderBy('RAND()')|first %}
  
  {% if leaderboard %}
    <div class="p-3 bg-white">
      <div class="w-full max-w-[728px] mx-auto rounded-[4px] overflow-hidden">
        {{ leaderboard.displayAd({
            'attr': {
              'class': 'leaderboard',
            },
        }) }}
      </div>
    </div>
  {% endif %}
{% endif %}
{# prettier-ignore-start #}
```

Inject
```
{{ sprig('_sprig/headerAds', {}, { 's-trigger': 'load' }) }}
```

![image](https://github.com/user-attachments/assets/24a00793-eb50-4a16-9fd9-3ac4ca8810f1)

**Comment by hafizovic** [comment]
> {# prettier-ignore-start #}

Looks like you're completely missing JS files from AdWizard

**Comment by diegocosta-dev** [comment]
> Looks like you're completely missing JS files from AdWizard

Yes, I was really forgetting. I managed to solve it based on this discussion.

https://github.com/doublesecretagency/craft-adwizard/issues/9#issuecomment-833375065

Thanks.
