### ISSUE TITLE
Issue with Image Transforms on Craft 4

### ISSUE THREAD

**Issue by LinneaHarts** [doublesecretagency/craft-adwizard#43]
I am getting an error when I try to pass in image transforms on craft 4.

getAssetTransforms is no longer supported in this way. https://docs.craftcms.com/api/v4/craft-web-application.html#public-methods

Here is the problem line: https://github.com/doublesecretagency/craft-adwizard/blob/v3-dev/src/models/Config.php#L150

And here's a screenshot of the error:
<img width="1295" alt="Screenshot 2023-05-10 at 16 27 18" src="https://github.com/doublesecretagency/craft-adwizard/assets/25594826/cc111adc-9f2d-42e0-9ce0-524358f57202">

**Comment by lindseydiloreto** [comment]
This is now fixed in [**v3.4.1**](https://github.com/doublesecretagency/craft-adwizard/releases/tag/3.4.1) (Craft 4) and [**v4.1.1**](https://github.com/doublesecretagency/craft-adwizard/releases/tag/4.1.1) (Craft 5).

Sorry this took such a long time to get sorted! 🙏
