### ISSUE TITLE
FrontEndAssets not being added?

### ISSUE THREAD

**Issue by cballenar** [doublesecretagency/craft-adwizard#52]
I'm having a really hard time wrapping my head around this one. 😵‍💫

The `aw.js` and `superagent.js` script tags are not being added to the rendered HTML _(even in prod which had been working well for months)_. 

I can't figure out if this is something happening on my browser (I've tried chrome, arc, firefox, safari and they all do the same thing), or something bizarre like it getting striped out on its way (mitm)?

Yesterday I tried it for a couple hours with no luck. This morning it seemed to work fine for a bit in local (ddev). And now it's broken again.

Anyone else seeing this? Any suggestions on what could be causing it or how to troubleshoot it?

Sorry if this seems off-the-wall but I'm not seeing this happening with anything else.

**Comment by lindseydiloreto** [comment]
Hi @cballenar, sorry for the late reply. Is it possible that you have some sort of ad blocker stripping out those two JS files?

Or perhaps there is some sort of caching issue going on? Do you have the ads wrapped in a `{% cache %}` tag?

Feel free to ping me on Discord if you're still having this issue, and we can troubleshoot it together.

**Comment by cballenar** [comment]
Thanks for follow up @lindseydiloreto . I believe this was related to an early version of  Craft 5.x. I couldn't figure out what was causing it but I recently updated to the latest version and I haven't seen the issue reoccur since then.

I'll go ahead and close this issue. Thanks!

**Comment by lindseydiloreto** [comment]
Ok great! Glad you got it sorted out. 🙏
