### ISSUE TITLE
adWizard is not defined

### ISSUE THREAD

**Issue by hatzipanis** [doublesecretagency/craft-adwizard#6]
I'm getting a console error: `adWizard is not defined` when clicking on an ad. My expected behaviour was for the URL associated with that ad to open.

**Comment by lindseydiloreto** [comment]
Out of curiosity, do you have that part of the page cached?

**Comment by hatzipanis** [comment]
This is a bit embarrassing but the issue was caused by uBlock Origin. Apologies for the time wasting!

**Comment by lindseydiloreto** [comment]
No worries, thanks for reporting back!
